### ISSUE TITLE
Does not yet support the current version of JupyterLab

### ISSUE THREAD

**Issue by tobias-fyi** [mohirio/jupyterlab-horizon-theme#3]
Recently when trying to install the theme I got the following error:

```
Extension Installation Error

An error occurred installing <code>@mohirio/jupyterlab-horizon-theme</code>.

Error message:

The extension "@mohirio/jupyterlab-horizon-theme" does not yet support the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab              Extension             Package
>=3.0.0-beta.4 <3.1.0   >=2.0.2 <3.0.0        @jupyterlab/application
>=3.0.0-beta.4 <3.1.0   >=2.0.2 <3.0.0        @jupyterlab/apputils
```

I like Horizon much more than the default dark theme. Whenever you get the chance to update this, it would be much appreciated!

Thanks!

**Comment by mohirio** [comment]
Absolutely @tobias-fyi! 
Thank you very much for notifying me, I didn't realize there was a new version of JupyterLab until recently, and I'll try to get to it this weekend!

**Comment by Alyetama** [comment]
Any update? It's still unsupported.

**Comment by cata0309** [comment]
Yes, an update would be great

**Comment by AxelTLarsson** [comment]
This is an excellent theme, so I would also very much appreciate an update!

**Comment by johannes-jansson** [comment]
Plus one 👌

**Comment by mohirio** [comment]
Hello everyone! 
I really apologize for long delay, but I'm happy to say that the extension is now upgraded to be compatible with Jupyterlab 3.0, and it is also installable with `pip`.
```bash
pip install juptyerlab-horizon-theme
```
It can also be installed the old way
```bash
jupyter labextension install @mohirio/jupyterlab-horizon-theme
```

I didn't have the chance to test it thoroughly yet, so I really appreciate any bug reporting or suggestions.

Cheers!
