### ISSUE TITLE
Theme overrides scrollPastEnd option

### ISSUE THREAD

**Issue by alabamagan** [mohirio/jupyterlab-horizon-theme#5]
I wasn't able to scroll past the last cell when I activate the theme.

**Comment by sbarrios93** [comment]
Same issue here, even though "scrollPastEnd" is set to true

**Comment by mohirio** [comment]
Thank you for reporting the issue, it took me so time to figure out what was the cause, but I believe it's fixed with in a12ea7076eb590ab2b7aa7e1346679aaf2dcacea.
