### ISSUE TITLE
JLab build fails

### ISSUE THREAD

**Issue by michaelaye** [mohirio/jupyterlab-horizon-theme#6]
Trying to install via the built-in plugin installer:

Build fails and the GUI recommends to run `jupyter lab build` in the terminal to get the full output. So I did:

```bash
─ jupyter lab build                                                                                                        ─╯
[LabBuildApp] WARNING | Config option `kernel_spec_manager_class` not recognized by `LabBuildApp`.
[LabBuildApp] JupyterLab 3.1.18
[LabBuildApp] Building in /home/maye/miniconda3/envs/py38/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (production, minimized)
Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (i.e., the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

An error occurred.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-ew5xq0qs.log
```

I put the log in this gist:

https://gist.github.com/michaelaye/409b18035a24900f3a68dcf8621c28c3

My system:
Ubuntu Linux, Python 3.8, based on conda-forge, all updates as of today:

```bash
╰─ mamba list jupyter                                                                                                       ─╯
# packages in environment at /home/maye/miniconda3/envs/py38:
#
# Name                    Version                   Build  Channel
jupyter                   1.0.0            py38h578d9bd_6    conda-forge
jupyter-lsp               1.4.1              pyhd8ed1ab_0    conda-forge
jupyter-server-mathjax    0.2.3              pyhd8ed1ab_0    conda-forge
jupyter-server-proxy      3.1.0              pyhd8ed1ab_0    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.0              pyhd8ed1ab_1    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_core              4.8.1            py38h578d9bd_0    conda-forge
jupyter_nbextensions_configurator 0.4.1            py38h578d9bd_2    conda-forge
jupyter_server            1.11.1             pyhd8ed1ab_0    conda-forge
jupyterlab                3.1.18             pyhd8ed1ab_0    conda-forge
jupyterlab-git            0.33.0             pyhd8ed1ab_0    conda-forge
jupyterlab-lsp            3.8.1              pyhd8ed1ab_0    conda-forge
jupyterlab_code_formatter 1.4.10             pyhd8ed1ab_1    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.8.2              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.2              pyhd8ed1ab_0    conda-forge
```

**Comment by J-Savage** [comment]
I'm having the exact same problem on Windows 10.

**Comment by alabamagan** [comment]
If you are using conda, try removing anything under `[env]/share/jupyter/lab/staging/node_modules/@mohirio` , build jupyter lab again, then install the theme again `pip install git+https://github.com/mohirio/jupyterlab-horizon-theme`
Now see if it appears on your jupyter lab "setting->theme" tab

**Comment by pinkneonsign** [comment]
Experiencing identical problem here on Win10.

**Comment by pinkneonsign** [comment]
> If you are using conda, try removing anything under `[env]/share/jupyter/lab/staging/node_modules/@mohirio` , build jupyter lab again, then install the theme again `pip install git+https://github.com/mohirio/jupyterlab-horizon-theme` Now see if it appears on your jupyter lab "setting->theme" tab

@alabamagan Was not able to install via pip and git as per your suggestion. Terminal output [here](https://gist.github.com/pinkneonsign/a43d52e58e685f9eee6c61e0e5fea289)

**Comment by alabamagan** [comment]
> > If you are using conda, try removing anything under `[env]/share/jupyter/lab/staging/node_modules/@mohirio` , build jupyter lab again, then install the theme again `pip install git+https://github.com/mohirio/jupyterlab-horizon-theme` Now see if it appears on your jupyter lab "setting->theme" tab
> 
> @alabamagan Was not able to install via pip and git as per your suggestion. Terminal output [here](https://gist.github.com/pinkneonsign/a43d52e58e685f9eee6c61e0e5fea289)

Could you also post the output you got running `pip install jupyterlab-horizon-theme`?

**Comment by pinkneonsign** [comment]
> > > If you are using conda, try removing anything under `[env]/share/jupyter/lab/staging/node_modules/@mohirio` , build jupyter lab again, then install the theme again `pip install git+https://github.com/mohirio/jupyterlab-horizon-theme` Now see if it appears on your jupyter lab "setting->theme" tab
> > 
> > 
> > @alabamagan Was not able to install via pip and git as per your suggestion. Terminal output [here](https://gist.github.com/pinkneonsign/a43d52e58e685f9eee6c61e0e5fea289)
> 
> Could you also post the output you got running `pip install jupyterlab-horizon-theme`?

`pip install jupyterlab-horizon-theme` worked! Here's the [output](https://gist.github.com/pinkneonsign/b2cf264b3018a083b12902924187ff19), although I think my error is because I use miniconda.

**Comment by pinkneonsign** [comment]
On a related note, I was able to use the theme without building, but code blocks would be cut off after only a few lines. Was solved by building lab and refreshing.

**Comment by alabamagan** [comment]
> On a related note, I was able to use the theme without building, but code blocks would be cut off after only a few lines. Was solved by building lab and refreshing.

Glad to hear that worked out for your. Apparently the code on npm, pypi and git might not be aligned.

**Comment by mohirio** [comment]
Thank you everyone for waiting so long, I'll be publishing a new version soon that aligns with the latest cookiecutter from Jupyterlab and it should fix all the issues.

**Comment by mohirio** [comment]
@michaelaye, @alabamagan @J-Savage @pinkneonsign 
The extension has been update to match the new cookiecutter and fixes various issues.
Please install with 
```
pip install jupyterlab-horizon-theme==3.1.1
```

You can install still it with npm, but pypi is the recommended way going forward.
```
jupyter labextension install @mohirio/jupyterlab-horizon-theme
```

Thank you for patience.
