### ISSUE TITLE
[Question] Styling plots

### ISSUE THREAD

**Issue by amzon-ex** [mohirio/jupyterlab-horizon-theme#9]
Hi, thanks for making this excellent theme.

How does one style matplotlib plots in line with this theme? The screenshot you've posted uses plotly - which I don't use, but I'm curious about getting a similar look.

**Comment by mohirio** [comment]
@amzon-ex Hey there, and thank you for your patience on this.

There are several ways to style matplotlib, I use the `matplotlibrc` file.
Basically you create a `~/.matplotlib/matplotlibrc` file with the following

```
lines.antialiased : True
text.color : ABB2BF
axes.labelcolor: ABB2BF
axes.edgecolor : 1C1E26
axes.grid : True
axes.prop_cycle : cycler('color', ['E06C75', '61AFEF', '98C379', 'D19A66', 'C678DD', '56B6C2', 'AAAAAA'])
xtick.color : ABB2BF
ytick.color : ABB2BF
grid.color : 5C6370

backend      : TkAgg
patch.facecolor        : 282C34
xtick.bottom         : False
xtick.direction      : in
ytick.left           : False
ytick.right          : False
ytick.direction      : infigure.figsize   : 16, 9
figure.dpi       : 100
figure.facecolor : 282C34
savefig.facecolor   : 282C34
```

And you'll get this look.
![Screen Shot 2022-12-04 at 17 55 28](https://user-images.githubusercontent.com/29782314/205482309-b20619c4-be84-4fa0-ae27-afe6ea343b51.png)

You can tweak and change the colors to get the desired look.
Here is a reference to matplotlibrc file: https://matplotlib.org/stable/tutorials/introductory/customizing.html#the-default-matplotlibrc-file
